<a href="https://colab.research.google.com/github/SahilJain8/DSC-ASSIGNMENT/blob/master/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([10, 20, 30])
a1
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [2, 3, 4]])
a2

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [ ]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Create an array of shape (5, 5) with only ones
a_one = np.ones([5,5])
a_one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create an array of shape (3, 3, 5) with only zeros
a_zero = np.zeros([3, 3, 5])
a_zero

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a_ran = np.random.randint(10, size=(7, 2))
a_ran

array([[4, 4],
       [5, 4],
       [5, 9],
       [8, 1],
       [6, 6],
       [1, 8],
       [3, 6]])

In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a_ran_fl = np.random.rand(3, 5)
a_ran_fl

array([[0.35396878, 0.34774863, 0.82472959, 0.02116081, 0.91771666],
       [0.40097797, 0.20151858, 0.6933827 , 0.98693971, 0.8832589 ],
       [0.36405761, 0.57652396, 0.58561089, 0.49834546, 0.86712371]])

In [ ]:
# Create an array of normally distributed random numbers
a_ran_nor = np.random.normal(size = (3,3))
a_ran_nor

array([[-1.3229441 , -1.67360963, -0.49283102],
       [-0.27128004, -1.66814056,  1.59589822],
       [ 2.62346347, -0.47455153,  0.15396653]])

In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
b_ran = np.random.randint(10, size = (4, 5))
b_ran

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1]])

In [ ]:
# Copy the code from the cell above and run it again
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
b_ran = np.random.randint(10, size = (4, 5))
b_ran

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5],
       [4, 1, 7, 5, 1]])

In [ ]:
# Find the 0'th index of the latest array you created
b_ran[0]

array([6, 3, 7, 4, 6])

In [ ]:
# Get the first 2 rows of latest array you created
b_ran[0:2, 0:5]

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4]])

In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
b_ran[:2, :2]

array([[6, 3],
       [9, 2]])

In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
x = np.random.randint(10, size=(3, 5))
print(x)
y = np.random.randint(10, size = (3, 5))
print(y)

[[6 8 7 0 7]
 [7 2 0 7 2]
 [2 0 4 9 6]]
[[9 8 6 8 7]
 [1 0 6 6 7]
 [4 2 7 5 2]]


In [ ]:
# Add the two arrays together
z = x+y
z

array([[15, 16, 13,  8, 14],
       [ 8,  2,  6, 13,  9],
       [ 6,  2, 11, 14,  8]])

In [ ]:
# Create another array of ones of shape (5, 3)
x_ones = np.ones([5, 3])
x_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
z + x_ones

ValueError: ignored

In [ ]:
# Do the same operation you just did but this time with a transpose on one array
x_ones.shape
x_ones = x_ones.reshape(3, 5)
sum = z + x_ones
sum

array([[16., 17., 14.,  9., 15.],
       [ 9.,  3.,  7., 14., 10.],
       [ 7.,  3., 12., 15.,  9.]])

In [ ]:
# Take the latest array to the power of 2 using the python way
p_py = sum*sum
p_py

array([[256., 289., 196.,  81., 225.],
       [ 81.,   9.,  49., 196., 100.],
       [ 49.,   9., 144., 225.,  81.]])

In [ ]:
# Do the same thing with numpy way
p_nu = np.power(sum, 2)
p_nu

array([[256., 289., 196.,  81., 225.],
       [ 81.,   9.,  49., 196., 100.],
       [ 49.,   9., 144., 225.,  81.]])

In [ ]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
np.mean(p_nu), np.max(p_nu), np.min(p_nu), np.std(p_nu), np.var(p_nu)

(132.66666666666666, 289.0, 9.0, 88.88769443641915, 7901.022222222221)

In [ ]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
m = np.random.randint(10, size = (3,3))
print(m)
n = np.random.randint(10, size = (3, 2))
n

[[0 2 4]
 [2 0 4]
 [9 6 6]]


array([[8, 9],
       [9, 2],
       [6, 0]])

In [ ]:
# Perform a dot product on the two newest arrays you created
dot_p = np.dot(m, n)
dot_p

array([[ 42,   4],
       [ 40,  18],
       [162,  93]])

In [ ]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
mm = np.random.randint(10, size = (4,3))
nn = np.random.randint(10, size = (4,3))

In [ ]:
# Perform a hadamard product on the two newest arrays you created
had = mm * nn
had

array([[12, 15, 12],
       [54, 36, 24],
       [36,  0,  0],
       [ 8, 72, 24]])

In [ ]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(mm, nn)

ValueError: ignored

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
mm = mm.reshape(3, 4)
np.dot(mm, nn)

array([[111,  81,  51],
       [103,  64,  48],
       [147,  95,  47]])

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
q = np.random.randint(10, size = (4,4))
r = np.random.randint(10, size = (4,4))

In [ ]:
# Compare the two arrays with '>', '<=' and '==' 
print(q > r)
print(q <= r)
print(q == r)

[[ True False  True False]
 [ True  True  True False]
 [ True  True  True  True]
 [ True  True False False]]
[[False  True False  True]
 [False False False  True]
 [False False False False]
 [False False  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [ ]:
# Sort one of the arrays you just created in ascending order
np.sort(q)

array([[2, 5, 6, 8],
       [0, 4, 7, 8],
       [2, 5, 7, 9],
       [0, 3, 7, 8]])

In [ ]:
# Sort the indexes of one of the arrays you just created
np.argsort(r)

array([[0, 2, 3, 1],
       [2, 0, 1, 3],
       [0, 2, 3, 1],
       [0, 1, 2, 3]])

In [ ]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(q, axis = 1)

array([0, 1, 1, 1])

In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(2, 100, 10)

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [ ]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(r, axis = 0)

array([1, 0, 3, 0])

In [ ]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(r, axis = 1)

array([0, 2, 0, 0])